### ISSUE TITLE
obs_node.out

### ISSUE THREAD

**Issue by uuuu-s** [phydrus/phydrus#14]
Hello.
I'm Yuushi.

Thank you for creating phydrus!
I tried to use it and worked well!

In obs_node.out file, the label is "h", "theta", "Temp" at each node,
but I think "h", "theta", "Flux" is correct.
It's not a serious problem, but could you confirm it?

Best regards,

**Comment by mvremec** [comment]
Hi Yuushi!

Thanks for the positive feedback! 

You can define whether Temperature or Flux is printed via. `ml.basic_info["lFlux"]` :
- .true. if fluxes are to be printed for observation nodes instead of temperatures,
- .false. if fluxes are not to be printed for observation nodes.

In Phydrus, "lFlux" is by default: False. This means Temperature is printed in the obs_node.out.

You can set it to True with:

`ml.basic_info["lFlux"] = True`

You can also find out whether "lFlux" is set to True/False in the SELECTOR.IN file.

Best,
Matevz

**Comment by uuuu-s** [comment]
Thank you for quick reply!
I meant obs_node.out label is "Temp" in spite of I set ml.basic_info["lFlux"] = True.
But I got it. Thank you very much!

**Comment by raoulcollenteur** [comment]
@mvremec is there something we need to change? If not, please close the issue.
